<?php

// @codingStandardsIgnoreFile

?>
<?php if (!empty($collection) && $collection->getSize()): ?>
    <div class="table-wrapper">
        <table class="data table ratings question summary">
            <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Ratings Question Summary'); ?></caption>
            <tbody>

            </tbody>
        </table>
    </div>
<?php endif; ?>
