<?php if ($block->getProductData()->getId()): ?>
<div class="product-question">
    <div class="page-title-wrapper">
        <h1><?php /* @escapeNotVerified */ echo __('Question Details') ?></h1>
    </div>
    <div class="product-img-box">
        <a href="<?php /* @escapeNotVerified */ echo $block->getProductData()->getProductUrl() ?>">
            <?php echo $block->getImage($block->getProductData(), 'product_base_image', ['class' => 'product-image'])->toHtml(); ?>
        </a>
        <?php if ($block->getRating() && $block->getRating()->getSize()): ?>
          <p><?php /* @escapeNotVerified */ echo __('Average Customer Rating') ?>:</p>
        <?php endif; ?>
    </div>
    <div class="details">
        <h3 class="product-name"><?php echo $block->escapeHtml($block->getProductData()->getName()) ?></h3>
        <?php if ($block->getRating() && $block->getRating()->getSize()): ?>
            <h4><?php /* @escapeNotVerified */ echo __('Product Rating:') ?></h4>
            <div class="table-wrapper">
                <table class="data-table question-summary-table">
                    <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Product Rating'); ?></caption>


                </table>
            </div>
        <?php endif; ?>
        <p class="date"><?php /* @escapeNotVerified */ echo __('Product Question (submitted on %1):', $block->dateFormat($block->getQuestionData()->getCreatedAt())) ?></p>
        <p><?php echo $block->getQuestionData()->getAnswerContent() ?></p>
    </div>
    <div class="actions">
        <div class="secondary">
            <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getBackUrl() ?>">
                <span><?php /* @escapeNotVerified */ echo __('Back to Product Questions') ?></a></span>
            </a>
        </div>
    </div>
</div>
<?php endif; ?>
