<?php

use NDP\Reviews\Helper\RelativeTime;

$format = IntlDateFormatter::SHORT;
$_items = $block->getQuestionsCollection()->getItems();
$page = $block->getCurrentPage();
$customerHelper = $this->helper('NDP\Customers\Helper\CustomerData');

?>

<?php if (count($_items)):?>

    <?php foreach ($_items as $_question):?>
    <div class="col-md-12 question-item">
        <div class="question-block block-content collapsed">
            <div class="block-top">
                <div class="user-panel">
                    <?php $questionCustomer = $_question->getCustomer(); ?>
                        <div class="polygon polygon-profile" >
                            <?php if ($questionCustomer != null): ?>
                                <div class="img" style="background-image: url(<?php echo $questionCustomer->getVisibleAvatar(); ?>)"></div>
                            <?php else: ?>
                                <img class="img" src="<?php echo $customerHelper->getDefaultAvatar(); ?>" alt="Avatar">
                            <?php endif;?>
                        </div>

                        <div class="review-details">
                            <?php if ($questionCustomer != null): ?>
                            <p class="customer-name"><?php echo $questionCustomer->getVisibleNickname(); ?></p>
                            <?php else: ?>
                                <p class="customer-name"></p>
                            <?php endif;?>
                        </div>
                </div>


                <div class="title-panel">
                    <h3><?php echo $block->escapeHtml($_question->getQuestionContent()) ?></h3>
                    <p class="date-question">
                    <time itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_question->getCreatedAt(), $format) ?>">
                        <?php /* @escapeNotVerified */ echo RelativeTime::getRelativeFormatedTime($_question->getCreatedAt()) ?>
                    </time>
                    </p>
                </div>

                <div class="colbtn-panel">
                    <button class="btn-invisible">
                        <span class="glyph glyph-collapse"></span>
                    </button>
                </div>
            </div>

            <!--Collapsing-->
            <div class="block-bottom">

                <div class="user-panel">
                    <div class="polygon polygon-profile-large polygon-white" >
                        <img class="img" src="<?php echo $this->getViewFileUrl('NDP_Question::images/ae_avatar.png'); ?>" alt="<?php /* @escapeNotVerified */ echo __('Airsoft Entrepôt') ?>">
                    </div>

                    <div class="review-details">
                        <p class="customer-name"><?php /* @escapeNotVerified */ echo __('Airsoft Entrepôt') ?></p>
                    </div>
                </div>

                <div class="content-panel">
                    <p><?php echo $_question->getAnswerContent() ?></p>
                </div>

            </div>
        </div>
    </div>
    <?php endforeach; ?>

    <div class="col-md-12 toolbar question-toolbar">
        <?php echo $block->getChildHtml('toolbar') ?>
    </div>

<?php elseif($page == 1): ?>

<div class="col-md-12 pager-loading ajax-remove">
    <p class="text-center">
       <?php /* @escapeNotVerified */ echo __('No question'); ?>
    </p>
</div>

<?php endif;?>
